export const STRINGS = {
  common: {
    cloudinaryMissingEnv:
      "Saknade Cloudinary-miljövariabler: EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME och EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET",
    cloudinaryUploadFailed: "Cloudinary-uppladdning misslyckades",
  },
  tabs: {
    home: "Hem",
    recipes: "Recept",
    menu: "Meny",
    account: "Konto",
    brand: "Unicorn Recipes",
  },
  home: {
    welcome: "Välkommen",
  },
  recipes: {
    title: "Mina recept",
    addRecipe: "+ Lägg till recept",
    empty: "Inga recept ännu. Lägg till ditt första!",
    fetchFailed: "Kunde inte hämta recept",
  },
  account: {
    title: "Konto",
    emailLabel: "E-post",
    signOut: "Logga ut",
  },
  auth: {
    signInTitle: "Logga in",
    signUpTitle: "Skapa konto",
    emailPlaceholder: "E-post",
    usernamePlaceholder: "Användarnamn",
    passwordPlaceholder: "Lösenord",
    verificationCodePlaceholder: "Verifieringskod",
    missingFieldsTitle: "Saknade fält",
    missingEmailPassword: "Ange e-post och lösenord.",
    missingUsername: "Ange ett användarnamn.",
    signUpNotReady: "Registrering är inte redo än.",
    signInNotReady: "Inloggning är inte redo än.",
    signInIncomplete: "Inloggningen slutfördes inte (status: {status}).",
    verifyEmailTitle: "Verifiera e-post",
    verifyEmailBody: "Vi skickade en verifieringskod till din e-post.",
    twoFactorTitle: "Tvåfaktorsautentisering",
    twoFactorBody: "Ange din {strategy}-kod.",
    noSecondFactor: "Inga tillgängliga metoder för två faktorer.",
    authFailed: "Autentisering misslyckades",
    verifyFailed: "Verifiering misslyckades",
    missingCodeTitle: "Saknad kod",
    missingEmailCode: "Ange verifieringskoden.",
    missingSecondFactorCode: "Ange din verifieringskod.",
    emailVerificationIncomplete: "E-postverifieringen slutfördes inte.",
    secondFactorIncomplete: "Verifiering med andra faktor slutfördes inte.",
    pleaseWait: "Vänta...",
    verify2FA: "Verifiera 2FA-kod",
    verifyEmail: "Verifiera e-post",
    createAccount: "Skapa konto",
    logIn: "Logga in",
    hasAccount: "Har du redan ett konto? Logga in",
    noAccount: "Har du inget konto? Skapa ett",
    secondFactorCodePlaceholder: "{strategy}-kod",
  },
  menu: {
    lunch: "Lunch",
    dinner: "Middag",
    unnamedMenu: "Namnlös meny",
    edit: "Redigera",
    cancel: "Avbryt",
    save: "Spara",
    saving: "Sparar...",
    menuNamePlaceholder: "Menynamn",
    menuNameOptionalPlaceholder: "Namn på meny (valfritt)",
    menuNameRequired: "Menynamn kan inte vara tomt",
    noMenuForWeek: "Ingen meny för den här veckan",
    createMenu: "Skapa meny",
    reusePrevious: "Återanvänd tidigare meny",
    genericError: "Något gick fel",
    fetchMenusFailed: "Kunde inte hämta menyer",
    createMenuFailed: "Kunde inte skapa meny",
    copyMenuFailed: "Kunde inte kopiera meny",
    updateMenuFailed: "Kunde inte uppdatera meny",
    delete: "Ta bort meny",
    deleting: "Tar bort meny...",
    deleteConfirmTitle: "Ta bort meny?",
    deleteConfirmBody:
      "Menyn och alla dess valda recept för veckan kommer att tas bort.",
    deleteMenuFailed: "Kunde inte ta bort meny",
    shoppingList: "Inköpslista",
  },
  shopping: {
    back: "← Tillbaka",
    title: "Inköpslista",
    startDate: "Startdatum",
    endDate: "Slutdatum",
    datePlaceholder: "ÅÅÅÅ-MM-DD",
    applyRange: "Uppdatera lista",
    invalidDateRange: "Startdatum måste vara samma som eller före slutdatum",
    fetchFailed: "Kunde inte hämta inköpslista",
    empty: "Inga ingredienser i det valda datumintervallet",
    conflictsTitle: "Enheter som inte kunde slås ihop",
  },
  menuPick: {
    titlePrefix: "Välj recept",
    back: "← Tillbaka",
    fetchFailed: "Kunde inte hämta recept",
    saveFailed: "Kunde inte spara",
    empty: "Inga sparade recept",
    genericError: "Något gick fel",
  },
  recipeDetail: {
    back: "← Tillbaka",
    edit: "Redigera",
    delete: "Ta bort",
    deleting: "Tar bort...",
    cancel: "Avbryt",
    deleteConfirmTitle: "Ta bort recept?",
    deleteConfirmBody:
      "Receptet tas bort från dina recept och från alla menyer där det används.",
    deleteFailedTitle: "Kunde inte ta bort",
    deleteFailed: "Kunde inte ta bort recept",
    notFound: "Recept hittades inte.",
    fetchFailed: "Kunde inte hämta recept",
    ingredients: "Ingredienser",
    instructions: "Instruktioner",
    video: "Video",
  },
  recipeNew: {
    back: "← Tillbaka",
    title: "Nytt recept",
    importTitle: "Importera",
    importDescription: "Fyll i formuläret från en bild eller recepttext.",
    uploading: "Importerar...",
    uploadFromDevice: "Ladda upp från enhet",
    scanning: "Skannar...",
    scanRecipe: "Skanna recept",
    createFromText: "Skapa från text",
    recipeTitle: "Recepttitel",
    recipeImage: "Receptbild",
    chooseImage: "Välj bild från bilder",
    takePhoto: "Ta foto",
    changeImage: "Byt bild",
    recipeVideoOptional: "Receptvideo (valfritt)",
    uploadVideo: "Ladda upp video från enhet",
    takeVideo: "Spela in video",
    changeVideo: "Byt video",
    addIngredient: "Lägg till ingrediens",
    amountPlaceholder: "Mängd",
    ingredientNamePlaceholder: "Ingrediensnamn",
    addIngredientButton: "Lägg till ingrediens",
    ingredients: "Ingredienser",
    noIngredients: "Inga ingredienser tillagda ännu.",
    remove: "Ta bort",
    instructions: "Instruktioner",
    instructionsPlaceholder: "Beskriv stegen...",
    save: "Spara recept",
    saving: "Sparar...",
    modalTitle: "Skapa från text",
    modalDescription:
      "Klistra in recepttext så fyller vi i fälten automatiskt.",
    modalPlaceholder: "Klistra in recepttext...",
    modalCancel: "Avbryt",
    modalImport: "Importera",
    modalImporting: "Importerar...",
    saveFailedTitle: "Kunde inte spara",
    importFailedTitle: "Import misslyckades",
    importReplaceTitle: "Ersätta nuvarande formulär?",
    importReplaceBody:
      "Import ersätter nuvarande titel, ingredienser och instruktioner.",
    importReplaceConfirm: "Ersätt",
    importSignInBody: "Logga in innan du importerar ett recept.",
    imageDescription: "Välj receptbild från bildbiblioteket eller ta ett foto.",
    parseIncompleteRecipe:
      "Kunde inte tolka ett komplett recept. Försök med tydligare text.",
    importInvalidData: "Servern returnerade ogiltig importdata.",
    permissionRequiredTitle: "Behörighet krävs",
    allowPhotoLibrary: "Tillåt åtkomst till bildbiblioteket.",
    allowCamera: "Tillåt kameratkomst.",
    noTextFound: "Ingen läsbar text hittades i bilden.",
    scanFailedTitle: "Skanning misslyckades",
    textRequiredTitle: "Text krävs",
    textRequiredBody: "Klistra in recepttext för att importera.",
    signInRequiredTitle: "Inloggning krävs",
    signInRequiredBody: "Logga in innan du skapar ett recept.",
  },
  recipeEdit: {
    back: "← Tillbaka",
    title: "Redigera recept",
    recipeTitle: "Titel",
    recipeTitlePlaceholder: "Recepttitel",
    recipeImage: "Receptbild",
    changeImage: "Byt bild",
    chooseImage: "Välj bild från bilder",
    takePhoto: "Ta foto",
    recipeVideoOptional: "Receptvideo (valfritt)",
    changeVideo: "Byt video",
    uploadVideo: "Ladda upp video från enhet",
    takeVideo: "Spela in video",
    removeVideo: "Ta bort video",
    addIngredient: "Lägg till ingrediens",
    amountPlaceholder: "Mängd",
    ingredientNamePlaceholder: "Ingrediensnamn",
    addIngredientButton: "Lägg till ingrediens",
    ingredients: "Ingredienser",
    noIngredients: "Inga ingredienser tillagda ännu.",
    remove: "Ta bort",
    instructions: "Instruktioner",
    instructionsPlaceholder: "Beskriv stegen...",
    saveChanges: "Spara ändringar",
    saving: "Sparar...",
    signInRequiredTitle: "Inloggning krävs",
    signInRequiredBody: "Logga in innan du redigerar ett recept.",
    loadFailedTitle: "Kunde inte ladda",
    updateFailedTitle: "Uppdatering misslyckades",
    fetchFailed: "Kunde inte ladda recept",
    noChangesTitle: "Inga ändringar",
    noChangesBody: "Uppdatera minst ett fält innan du sparar.",
    updateFailed: "Kunde inte uppdatera recept",
    permissionRequiredTitle: "Behörighet krävs",
    allowPhotoLibrary: "Tillåt åtkomst till bildbiblioteket.",
    allowCamera: "Tillåt kameratkomst.",
  },
} as const;
